import os
import subprocess
os.system("clear")
os.system("pip install subprocess")
os.system("apt install git")
os.system("webbrowser")
os.system("clear")
print("")
print("\033[1;31m$$$$$$$$\ $$\ $$\      $$\  $$$$$$\ \033[1;34m $$$$$$$$\  $$$$$$\   $$$$$$\  ")
print("\033[1;31m$$  _____|$$ |$$$\    $$$ |$$  __$$\ \033[1;34m\____$$  |$$ ___$$\ $$  __$$\ ")
print("\033[1;31m$$ |      $$ |$$$$\  $$$$ |$$ /  $$ | \033[1;34m   $$  / \_/   $$ |$$ /  \__|")
print("\033[1;31m$$$$$\    $$ |$$\$$\$$ $$ |$$ |  $$ | \033[1;34m  $$  /    $$$$$ / $$ |$$$$\ ")
print("\033[1;31m$  __|    $$ |$$ \$$$  $$ |$$ |  $$ | \033[1;34m $$  /     \___$$\ $$ |\_$$ | ")
print("\033[1;31m$$ |      $$ |$$ |\$  /$$ |$$ |  $$ \033[1;34m| $$  /    $$\   $$ |$$ |  $$ |")
print("\033[1;31m$$$$$$$$\ $$ |$$ | \_/ $$ | $$$$$$  \033[1;34m|$$$$$$$$\ \$$$$$$  |\$$$$$$  |")
print("\033[1;31m\________|\__|\__|     \__| \______/\033[1;34m \________| \______/  \______/ ")
print("")
print("\033[1;30m="*50)
print("     https://www.youtube.com/@ElMOZ3G12")
print("     https://t.me/ElMOZ3G12")
print("     https://github.com/mohamedmayallo90")
print("\033[1;30m="*50)
print("                                                                                       ")
print("\033[1;30mDownload the most famous hacking tools:")
print("\033[1;30mNote: This tool works on Kali Linux!")
print("="*37)
dow =input("\033[1;32mDownload the tool \033[1;31my|n: ")
if dow == "y":
    os.system("git clone https://github.com/mohamedmayallo90/the-tool.git")       
    print("\033[1;31mDone")
else:
    print("Please restart the tool ")           